# Generated by Django 4.2.4 on 2023-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='average_interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='next_event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
