# Generated by Django 4.2.4 on 2024-01-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_average_interval_days_event_next_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="comments",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
